name       : nvidia-docker
version    : 2.5.0
release    : 2
source     :
    - https://github.com/NVIDIA/nvidia-docker/archive/v2.5.0.tar.gz : 2e97c810be86e59a241e955286c15259b9986ede1e7610691e75e9e91b2d8abb
license    : Apache-2.0
component  : programming.tools
summary    : nvidia-docker CLI wrapper
description: |
    Build and run Docker containers leveraging NVIDIA GPUs
rundeps    :
    - docker
    - nvidia-container-runtime
install    : |
    install -Dm00755 $workdir/nvidia-docker $installdir/usr/bin/nvidia-docker
    install -dm00755 $installdir/etc/docker
    install -Dm00644 $workdir/daemon.json $installdir/etc/docker/daemon.json
