name       : nvidia-docker
version    : 2.0.3
release    : 1
source     :
    - https://github.com/NVIDIA/nvidia-docker/archive/v2.0.3.tar.gz : f94c963b6d2a537711c7e8e9e3c3fe3d9f9fddc48599d5a411119276a33763db
license    : BSD-3-Clause
component  : programming.tools
summary    : nvidia-docker CLI wrapper
description: |
   Build and run Docker containers leveraging NVIDIA GPUs 
rundeps    :
    - docker
    - nvidia-container-runtime
install    : |
    install -Dm00755 $workdir/nvidia-docker $installdir/usr/bin/nvidia-docker
    install -dm00755 $installdir/etc/docker
    install -Dm00644 $workdir/daemon.json $installdir/etc/docker/daemon.json
